[package]
name = "efibootmgr"
version = "18"
release = 4
slot = "0"
description = "Linux user-space application to modify the EFI Boot Manager"
license = "GPL-2.0-or-later"
upstream = "https://github.com/rhboot/efibootmgr"

[dependencies]
runtime = ["glibc", "popt"]
build = ["gcc", "efivar", "git"]

[sources]
urls = [
    "https://github.com/rhboot/efibootmgr/archive/refs/tags/18.tar.gz"
]
sha256 = ["442867d12f8525034a404fc8af3036dba8e1fc970998af2486c3b940dfad0874"]

[build]
type = "custom"
script = """
cd "${srcdir}/efibootmgr-${pkgver}"
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
