[package]
name = "vulkan-headers"
version = "1.4.364"
release = 1
slot = "0"
description = "Vulkan Header files and API registry"
license = "Apache-2.0"
upstream = "https://github.com/KhronosGroup/Vulkan-Headers"

[dependencies]
runtime = []
build = ["cmake", "ninja"]

[sources]
urls = [
  "https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v1.4.363.tar.gz"
]
sha256 = [
    "37e00e30611375938a9437477de793e355e55d486c25ab3dfd7a1a11ab0f8f07"
]

[build]
type = "cmake"
script = """
cmake -B build -G Ninja \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_BUILD_TYPE=Release \
  -DVULKAN_HEADERS_ENABLE_TESTS=OFF

ninja -C build
DESTDIR="${DESTDIR}" ninja -C build install
"""
