[package]
name = "meson"
version = "1.12.1"
release = 1
slot = "0"
description = "Fast and user friendly build system"
license = "Apache-2.0"
upstream = "https://mesonbuild.com/"

[dependencies]
runtime = ["glibc", "python", "ninja"]
build = ["python"]

[sources]
urls = [
    "https://github.com/mesonbuild/meson/releases/download/1.12.0/meson-1.12.0.tar.gz"
]
sha256 = [
    "ab0a6ca09f8ef70c564c8241fb5a23957886a0b53fb58412b5e07eaf07dba743"
]

[build]
type = "custom"
script = """
cd "${srcdir}/meson-${pkgver}"
python setup.py build
python setup.py install --root="${DESTDIR}" --prefix=/usr --optimize=1
"""
