[package]
name = "helix"
version = "25.07.1"
release = 2
slot = "0"
description = "A post-modern modal text editor"
license = "GPL-2.0-or-later"
upstream = "https://helix-editor.com"

[dependencies]
runtime = ["glibc", "gcc"]
build = ["gcc", "rust", "mold", "clang", "llvm", "pkgconf", "git"]

[sources]
urls = [
    "https://github.com/helix-editor/helix/archive/refs/tags/25.07.1.tar.gz"
]
sha256 = ["27c8bc3eba46bc7bab1e3629c6b28ff94882eeff17366b3ea69cd8ceffba7541"]

[build]
type = "cargo"
script = """
cd "${srcdir}/helix-${pkgver}"
cargo build --release --locked
install -Dm755 "target/release/helix" "${DESTDIR}/usr/bin/helix"
"""
