[package]
name = "neovim"
version = "0.12.6"
release = 1
slot = "0"
description = "Vim-fork focused on extensibility and usability"
license = "Apache-2.0"
upstream = "https://neovim.io/"

[dependencies]
runtime = ["glibc"]
build = ["cmake", "ninja", "gcc", "pkgconf"]

[sources]
urls = [
    "https://github.com/neovim/neovim/archive/refs/tags/v0.12.5.tar.gz"
]
sha256 = [
    "8629fdc5eb951daf89a76f68cad12f2f1e03fab0d539150ba3fe6d177d254b7f"
]

[build]
type = "cmake"
script = """
cd "${srcdir}/neovim-${pkgver}"
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
ninja -C build ${MAKEFLAGS}
DESTDIR="${DESTDIR}" ninja -C build install
"""
