[package]
name = "neovim"
version = "0.12.5"
release = 1
slot = "0"
description = "Vim-fork focused on extensibility and usability"
license = "Apache-2.0"
upstream = "https://neovim.io/"

[dependencies]
runtime = [
    "glibc",
]
build = [
    "cmake",
    "ninja",
    "gcc",
    "pkgconf",
]

[sources]
urls = [
    "https://github.com/neovim/neovim/archive/refs/tags/v0.12.5.tar.gz",
]
sha256 = ["a810c95332317bd0017e1ca07e376a8472c79075cbed00fa3737d190a8a0a45a"]

[build]
type = "cmake"
script = """
cd "${srcdir}/neovim-${pkgver}"
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
ninja -C build ${MAKEFLAGS}
DESTDIR="${DESTDIR}" ninja -C build install
"""
