[package]
name = "vulkan-loader"
version = "1.4.363"
release = 1
slot = "0"
description = "Vulkan Installable Client Driver (ICD) Loader"
license = "Apache-2.0"
upstream = "https://github.com/KhronosGroup/Vulkan-Loader"

[dependencies]
runtime = ["glibc", "vulkan-headers", "wayland"]
build = ["cmake", "ninja", "pkgconf", "python"]

[sources]
urls = [
  "https://github.com/KhronosGroup/Vulkan-Loader/archive/refs/tags/v1.4.363.tar.gz"
]
sha256 = [
  "cc520304a4d8de9a6a1699553d6090aef0c25f87ef6cbc16b7c84ebd99093264"
]

[build]
type = "cmake"
script = """
cmake -B build -G Ninja \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_SYSCONFDIR=/etc \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DBUILD_TESTS=OFF

ninja -C build
DESTDIR="${DESTDIR}" ninja -C build install
"""
