[package]
name = "nushell"
version = "0.116.0"
release = 1
slot = "0"
description = "A new type of shell"
license = "MIT"
upstream = "https://www.nushell.sh"

[dependencies]
runtime = ["glibc", "curl", "gcc", "libgit2", "libssh2", "openssl", "sqlite", "zstd"]
build = ["gcc", "rust", "mold", "llvm", "pkgconf", "git"]

[sources]
urls = [
    "https://github.com/nushell/nushell/archive/refs/tags/0.115.1.tar.gz"
]
sha256 = [
    "1174d023ffc8083750daec8ee2dfe6486a8ef9f5c22396aa675b61d1bb0fad2d"
]

[build]
type = "custom"
script = """
cd "${srcdir}/nushell-${pkgver}"
cargo build --release --locked
install -Dm755 "target/release/nushell" "${DESTDIR}/usr/bin/nushell"
"""
