[package]
name = "mkinitcpio"
version = "42.1"
release = 1
slot = "0"
description = "Modular and fast initramfs creation utility for Linux"
license = "GPL-2.0-only"
upstream = "https://wiki.archlinux.org/title/Mkinitcpio"

[dependencies]
runtime = ["bash", "kmod", "coreutils", "util-linux", "zstd", "findutils"]
build = ["make"]

[sources]
urls = [
    "https://github.com/archlinux/mkinitcpio/archive/refs/tags/v42.tar.gz"
]
sha256 = [
    "6d81a44e737d235dfcb843277135a669915e4e64fa2143631e7d86fd6a943dd9"
]

[build]
type = "custom"
script = """
cd "${srcdir}/mkinitcpio-${pkgver}"
make DESTDIR="${DESTDIR}" PREFIX=/usr install
"""
