[package]
name = "bubblewrap"
version = "0.11.0"
release = 1
slot = "0"
description = "Unprivileged sandboxing tool based on Linux user namespaces"
license = "LGPL-2.0-or-later"
upstream = "https://github.com/containers/bubblewrap"

[dependencies]
runtime = ["glibc", "libcap"]
build = ["meson", "ninja", "pkgconf", "gcc"]

[sources]
urls = [
    "https://github.com/containers/bubblewrap/releases/download/v0.11.0/bubblewrap-0.11.0.tar.xz"
]
sha256 = [
    "988fd6b232dafa04b8b8198723efeaccdb3c6aa9c1c7936219d5791a8b7a8646"
]

[build]
type = "meson"
script = """
cd "${srcdir}/bubblewrap-${pkgver}"
meson setup build --prefix=/usr --buildtype=release -Dman=disabled -Drequire_userns=true
ninja -C build ${MAKEFLAGS}
DESTDIR="${DESTDIR}" ninja -C build install
"""
