[package]
name = "mpc"
version = "1.4.1"
release = 1
slot = "0"
description = "Library for the arithmetic of complex numbers with arbitrarily high precision"
license = "LGPL-3.0-or-later"
upstream = "https://www.multiprecision.org/mpc/"

[dependencies]
runtime = [
    "glibc",
    "gmp",
    "mpfr",
]
build = [
    "make",
    "gcc",
]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/mpc/mpc-1.4.1.tar.gz",
]
sha256 = []

[build]
type = "autotools"
script = """
cd "${srcdir}/mpc-${pkgver}"
./configure --prefix=/usr
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
