[package]
name = "hwdata"
version = "0.411"
release = 1
slot = "0"
description = "Hardware identification databases (pci.ids, usb.ids, oui.txt)"
license = "GPL-2.0-or-later"
upstream = "https://github.com/vcrhonek/hwdata"

[dependencies]
runtime = ["glibc"]
build = ["make"]

[sources]
urls = [
    "https://github.com/vcrhonek/hwdata/archive/refs/tags/v0.411.tar.gz"
]
sha256 = ["d75462181fbd307228e0a48b8d1449f1773ea4b1f17e8a1d56346907f999ce33"]

[build]
type = "autotools"
script = """
cd "${srcdir}/hwdata-0.392"
./configure --prefix=/usr --sysconfdir=/etc --datadir=/usr/share
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
