[package]
name = "gcc"
version = "16.2.0"
release = 1
slot = "15"
description = "GNU Compiler Collection (C and C++ Compilers - Latest 15.3)"
license = "GPL-3.0-or-later WITH GCC-exception-3.1"
upstream = "https://gcc.gnu.org/"

[dependencies]
runtime = ["glibc", "gmp", "mpfr", "mpc", "zstd"]
build = ["bison", "flex"]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/gcc/gcc-16.2.0/gcc-16.2.0.tar.xz"
]
sha256 = ["e6738e29597f733270731aa90600f37ffdc045079dfc27ec7e8192cc81085c3e"]

[build]
type = "autotools"
script = """
mkdir -p build && cd build
../gcc-${pkgver}/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --enable-languages=c,c++ --enable-default-pie --enable-default-ssp --disable-multilib --disable-bootstrap --disable-werror --with-system-zlib
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
