[package]
name = "gmp"
version = "6.3.0"
release = 1
slot = "0"
description = "GNU Multiple Precision Arithmetic Library"
license = "LGPL-3.0-or-later OR GPL-2.0-or-later"
upstream = "https://gmplib.org/"

[dependencies]
runtime = ["glibc"]
build = ["m4"]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz"
]
sha256 = ["a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898"]

[build]
type = "autotools"
script = """
cd "${srcdir}/gmp-${pkgver}"
./configure --prefix=/usr --enable-cxx
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
