[package]
name = "ca-certificates"
version = "20241121"
release = 1
slot = "0"
description = "Common CA root certificates bundle from Mozilla"
license = "MPL-2.0"
upstream = "https://curl.se/docs/caextract.html"

[dependencies]
runtime = [
    "openssl",
]
build = [
    "python",
]

[sources]
urls = [
    "https://curl.se/ca/cacert-2024-11-26.pem",
]
sha256 = []

[build]
type = "custom"
script = """
mkdir -p "${DESTDIR}/etc/ssl/certs"
cp "${srcdir}/cacert-2024-11-26.pem" "${DESTDIR}/etc/ssl/certs/ca-certificates.crt"
ln -sf certs/ca-certificates.crt "${DESTDIR}/etc/ssl/cert.pem"
"""
