[package]
name = "qt6-svg"
version = "6.8.2"
release = 1
description = "Classes for displaying the contents of SVG files in Qt6"
license = "LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only"
homepage = "https://www.qt.io/"
slot = "6"

[dependencies]
depends = ["qt6-base", "zlib"]
makedepends = ["cmake", "ninja", "pkgconf"]

[sources]
urls = ["https://download.qt.io/official_releases/qt/6.8/6.8.2/submodules/qtsvg-everywhere-src-6.8.2.tar.xz"]
sha256 = ["aa2579f21ca66d19cbcf31d87e9067e07932635d36869c8239d4decd0a9dc1fa"]

[build]
configure = """
cmake -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DINSTALL_BINDIR=lib/qt6/bin \
    -DINSTALL_INCLUDEDIR=include/qt6 \
    -DINSTALL_LIBDIR=lib \
    -DINSTALL_ARCHDATADIR=lib/qt6 \
    -DINSTALL_PLUGINSDIR=lib/qt6/plugins \
    -DBUILD_TESTING=OFF
"""
compile = """
cmake --build build -j$(nproc)
"""
install = """
DESTDIR="${DESTDIR}" cmake --install build
"""
