[package]
name = "elfutils"
version = "0.192"
release = 1
slot = "0"
description = "Libraries and tools for handling ELF files and DWARF data"
license = "GPL-3.0-or-later AND (GPL-2.0-or-later OR LGPL-3.0-or-later)"
upstream = "https://sourceware.org/elfutils/"

[dependencies]
runtime = ["glibc", "zlib", "bzip2", "xz", "zstd"]
build = ["make", "gcc", "pkgconf", "m4", "flex", "bison"]

[sources]
urls = [
    "https://sourceware.org/elfutils/ftp/0.192/elfutils-0.192.tar.bz2"
]
sha256 = [
    "616099beae24aba11f9b63d86ca6cc8d566d968b802391334c91df54eab416b4"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/elfutils-${pkgver}"
./configure --prefix=/usr --disable-debuginfod --enable-libdebuginfod=dummy
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
