[package]
name = "doas"
version = "6.8.2"
release = 1
slot = "0"
description = "Simple OpenBSD privilege escalation tool ported to Linux"
license = "ISC"
upstream = "https://github.com/Duncaen/OpenDoas"

[dependencies]
runtime = [
    "glibc",
]
build = [
    "make",
    "gcc",
    "bison",
    "flex",
]

[sources]
urls = [
    "https://github.com/Duncaen/OpenDoas/archive/refs/tags/v6.8.2.tar.gz",
]
sha256 = []

[build]
type = "make"
script = """
cd "${srcdir}/OpenDoas-${pkgver}"
./configure --prefix=/usr --sysconfdir=/etc --without-pam
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
