[package]
name = "cmake"
version = "4.4.4"
release = 1
slot = "0"
description = "Cross-platform open-source build system generator"
license = "BSD-3-Clause"
upstream = "https://cmake.org/"

[dependencies]
runtime = ["glibc", "openssl", "zlib", "libarchive"]
build = ["make", "gcc", "binutils", "pkgconf"]

[sources]
urls = [
    "https://github.com/Kitware/CMake/releases/download/v4.3.5/cmake-4.3.5.tar.gz"
]
sha256 = [
    "bd24c30d80a7744ae84b845ff080cc8453b06c622ef01066564108e9cefc44cf"
]

[build]
type = "custom"
script = """
cd "${srcdir}/cmake-${pkgver}"
./bootstrap --prefix=/usr --parallel=${MAKEFLAGS#-j} --system-libs --no-system-jsoncpp --no-system-cppdap
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
