[package]
name = "cmake"
version = "4.3.5"
release = 1
slot = "0"
description = "Cross-platform open-source build system generator"
license = "BSD-3-Clause"
upstream = "https://cmake.org/"

[dependencies]
runtime = ["glibc", "openssl", "zlib", "libarchive"]
build = ["make", "gcc", "binutils", "pkgconf"]

[sources]
urls = [
    "https://github.com/Kitware/CMake/releases/download/v4.3.5/cmake-4.3.5.tar.gz"
]
sha256 = ["24fc974191ef48da4ff309671fdb5989f43e07ecde0e2589eaf9d72672d8612b"]

[build]
type = "custom"
script = """
cd "${srcdir}/cmake-${pkgver}"
./bootstrap --prefix=/usr --parallel=${MAKEFLAGS#-j} --system-libs --no-system-jsoncpp --no-system-cppdap
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
