[package]
name = "elogind"
version = "257.16"
release = 1
slot = "0"
description = "The systemd project"
license = "GPL-2.0-or-later"
upstream = "https://github.com/elogind/elogind"

[dependencies]
runtime = ["glibc", "pam", "acl", "libcap"]
build = ["gcc", "intltool", "libtool", "gperf", "libcap", "meson", "ninja", "pkgconf"]

[sources]
urls = [
    "https://github.com/elogind/elogind/archive/refs/tags/v257.16.tar.gz"
]
sha256 = ["3c8146409bfb9daa77f272212c2b0bf0ae727c782ec87ece0d2d25e0e5bf5f4c"]

[build]
type = "meson"
script = """
cd "${srcdir}/elogind-${pkgver}"
meson setup build --prefix=/usr --buildtype=release
ninja -C build ${MAKEFLAGS}
DESTDIR="${DESTDIR}" ninja -C build install
"""
