[package]
name = "fzf"
version = "0.74.4"
release = 1
slot = "0"
description = "Command-line fuzzy finder"
license = "("
upstream = "https://github.com/junegunn/fzf"

[dependencies]
runtime = ["glibc"]
build = ["gcc", "git", "go"]

[sources]
urls = [
    "https://github.com/fzf/fzf/archive/refs/tags/v0.74.4.tar.gz"
]
sha256 = []

[build]
type = "custom"
script = """
cd "${srcdir}/fzf-${pkgver}"
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
