[package]
name = "tokei"
version = "15.0.0"
release = 1
slot = "0"
description = "A blazingly fast CLOC (Count Lines Of Code) program"
license = "("
upstream = "https://github.com/XAMPPRocky/tokei"

[dependencies]
runtime = ["glibc", "gcc"]
build = ["gcc", "rust", "cargo"]

[sources]
urls = [
    "https://github.com/XAMPPRocky/tokei/archive/v15.0.0.tar.gz"
]
sha256 = []

[build]
type = "custom"
script = """
cd "${srcdir}/tokei-${pkgver}"
cargo build --release --locked
install -Dm755 "target/release/tokei" "${DESTDIR}/usr/bin/tokei"
"""
