[package]
name = "squashfs-tools"
version = "4.7.5"
release = 1
slot = "0"
description = "Tools for squashfs, a highly compressed read-only filesystem for Linux"
license = "GPL-2.0-or-later"
upstream = "https://github.com/plougher/squashfs-tools"

[dependencies]
runtime = ["glibc", "gcc", "lz4", "lzo", "xz", "zlib", "zstd"]
build = ["gcc", "help2man"]

[sources]
urls = [
    "https://github.com/plougher/squashfs-tools/archive/refs/tags/4.7.5.tar.gz"
]
sha256 = ["547b7b7f4d2e44bf91b6fc554664850c69563701deab9fd9cd7e21f694c88ea6"]

[build]
type = "custom"
script = """
cd "${srcdir}/squashfs-tools-${pkgver}"
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
