[package]
name = "ethtool"
version = "7.1"
release = 1
slot = "0"
description = "Utility for examining and tuning network interfaces and drivers"
license = "GPL-2.0-only"
upstream = "https://kernel.org/pub/software/network/ethtool/"

[dependencies]
runtime = ["glibc"]
build = ["make", "gcc", "pkgconf"]

[sources]
urls = [
    "https://www.kernel.org/pub/software/network/ethtool/ethtool-7.1.tar.xz"
]
sha256 = [
    "4d78c26edc0255bc92f4b995b5fd66108d75ff966ed4694f6025a6d370bc2496"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/ethtool-${pkgver}"
./configure --prefix=/usr
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
