[package]
name = "libevdev"
version = "1.13.7"
release = 1
slot = "0"
description = "Wrapper library for evdev devices"
license = "MIT"
upstream = "https://www.freedesktop.org/wiki/Software/libevdev/"

[dependencies]
runtime = ["glibc"]
build = ["meson", "ninja", "gcc", "pkgconf", "python"]

[sources]
urls = [
    "https://www.freedesktop.org/software/libevdev/libevdev-1.13.7.tar.xz"
]
sha256 = [
    "0caf824971108f15bb2ad356433bae198d7d3bf1e82d43f63626e069e060bfa6"
]

[build]
type = "meson"
script = """
cd "${srcdir}/libevdev-${pkgver}"
meson setup build --prefix=/usr --buildtype=release -Ddocumentation=disabled -Dtests=disabled
ninja -C build -j${FORGE_JOBS:-$(nproc)}
DESTDIR="${DESTDIR}" ninja -C build install
"""
