[package]
name = "dust"
version = "1.2.6"
release = 1
slot = "0"
description = "A more intuitive version of du in rust"
license = "Apache-2.0"
upstream = "https://github.com/bootandy/dust"

[dependencies]
runtime = ["glibc", "gcc"]
build = ["gcc", "git", "rust"]

[sources]
urls = [
    "https://github.com/bootandy/dust/archive/refs/tags/v1.2.6.tar.gz"
]
sha256 = ["9dd1ec7576d43574e6f48342cb96a5087338b4c308460a848f5895f72ddc3bc9"]

[build]
type = "cargo"
script = """
cd "${srcdir}/dust-${pkgver}"
cargo build --release --locked
install -Dm755 "target/release/dust" "${DESTDIR}/usr/bin/dust"
"""
