[package]
name = "sqlite"
version = "3.53.4"
release = 1
slot = "0"
description = "Self-contained serverless SQL database engine"
license = "blessing"
upstream = "https://www.sqlite.org/"

[dependencies]
runtime = ["glibc", "readline", "zlib"]
build = ["make", "gcc", "pkgconf"]

[sources]
urls = [
    "https://www.sqlite.org/2025/sqlite-autoconf-3490100.tar.gz"
]
sha256 = ["106642d8ccb36c5f7323b64e4152e9b719f7c0215acf5bfeac3d5e7f97b59254"]

[build]
type = "autotools"
script = """
cd "${srcdir}/sqlite-autoconf-3490100"
./configure --prefix=/usr --enable-readline --enable-threadsafe
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
