[package]
name = "grub"
version = "2.14"
release = 1
description = "GNU GRand Unified Bootloader (2)"
license = "GPL-3.0-or-later"
upstream = "https://www.gnu.org/software/grub/"
slot = "0"

[dependencies]
runtime = ["glibc", "xz"]
build = ["gcc", "make", "pkgconf", "flex", "bison", "python"]

[sources]
urls = ["https://ftp.gnu.org/gnu/grub/grub-2.14.tar.xz"]
sha256 = ["bc8d3c73535b8838d8c8e2654d73edc4e6ae8c8acdb45d5df5dc9a1547446d43"]

[build]
compiler_override = "gcc"
disable_custom_march = true
cflags = "-O2 -pipe"
configure = """
./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-werror \
    --disable-static
"""
compile = """
make -j$(nproc)
"""
install = """
make DESTDIR="${DESTDIR}" install
"""
