[package]
name = "forge-binhost"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
forge-core = { path = "../forge-core" }
forge-cpu = { path = "../forge-cpu" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
zstd = { workspace = true }
tar = { workspace = true }
