[package]
name = "libinih"
version = "62"
release = 1
slot = "0"
description = "Simple INI file parser written in C"
license = "BSD-3-Clause"
upstream = "https://github.com/benhoyt/inih"

[dependencies]
runtime = ["glibc"]
build = ["meson", "ninja", "gcc", "pkgconf"]

[sources]
urls = [
    "https://github.com/benhoyt/inih/archive/refs/tags/r62.tar.gz"
]
sha256 = [
    "9c15fa751bb8093d042dae1b9f125eb45198c32c6704cd5481ccde460d4f8151"
]

[build]
type = "meson"
script = """
cd "${srcdir}/inih-r${pkgver}"
meson setup build --prefix=/usr --buildtype=release -Ddistro_install=true
ninja -C build -j${FORGE_JOBS:-$(nproc)}
DESTDIR="${DESTDIR}" ninja -C build install
"""
