[package]
name = "libpciaccess"
version = "0.19"
release = 1
slot = "0"
description = "Generic PCI access library"
license = "MIT"
upstream = "https://xorg.freedesktop.org/"

[dependencies]
runtime = ["glibc", "zlib"]
build = ["meson", "ninja", "gcc", "pkgconf"]

[sources]
urls = [
    "https://www.x.org/releases/individual/lib/libpciaccess-0.19.tar.xz"
]
sha256 = [
    "3c55aa86c82e54a4e3109786f0463530d53b36b6d1cfd14616454f985dd2aa43"
]

[build]
type = "meson"
script = """
cd "${srcdir}/libpciaccess-${pkgver}"
meson setup build --prefix=/usr --buildtype=release -Dzlib=enabled
ninja -C build -j${FORGE_JOBS:-$(nproc)}
DESTDIR="${DESTDIR}" ninja -C build install
"""
