[package]
name = "bc"
version = "1.08.2"
release = 1
slot = "0"
description = "Arbitrary precision numeric processing language"
license = "GPL-3.0-or-later"
upstream = "https://www.gnu.org/software/bc/"

[dependencies]
runtime = ["glibc", "readline"]
build = ["make", "gcc", "flex", "bison"]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/bc/bc-1.08.2.tar.gz"
]
sha256 = [
    "ae470fec429775653e042015edc928d07c8c3b2fc59765172a330d3d87785f86"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/bc-${pkgver}"
./configure --prefix=/usr --with-readline --mandir=/usr/share/man --infodir=/usr/share/info
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
