[package]
name = "rsync"
version = "3.5.0"
release = 1
slot = "0"
description = "Fast and versatile remote file copying tool"
license = "GPL-3.0-or-later"
upstream = "https://rsync.samba.org/"

[dependencies]
runtime = [
    "glibc",
    "zstd",
    "openssl",
    "acl",
]
build = [
    "make",
    "gcc",
    "pkgconf",
]

[sources]
urls = [
    "https://download.samba.org/pub/rsync/src/rsync-3.5.0.tar.gz",
]
sha256 = ["c7ffd1ef653e99540f661e47cb00b7f9cad1ee6b972399b16f93d672656e0d33"]

[build]
type = "autotools"
script = """
cd "${srcdir}/rsync-${pkgver}"
./configure --prefix=/usr --with-included-popt=yes --with-included-zlib=no --disable-lz4 --disable-xxhash
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
