[package]
name = "rsync"
version = "3.5.1"
release = 1
slot = "0"
description = "Fast and versatile remote file copying tool"
license = "GPL-3.0-or-later"
upstream = "https://rsync.samba.org/"

[dependencies]
runtime = ["glibc", "zstd", "openssl", "acl"]
build = ["make", "gcc", "pkgconf"]

[sources]
urls = [
    "https://download.samba.org/pub/rsync/src/rsync-3.5.0.tar.gz"
]
sha256 = [
    "c55f9c9dc10fb8bec397b399a0fdded53cc9a2d8e30891bb0d63724d25c37bef"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/rsync-${pkgver}"
./configure --prefix=/usr --with-included-popt=yes --with-included-zlib=no --disable-lz4 --disable-xxhash
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
