[package]
name = "tar"
version = "1.35"
release = 1
slot = "0"
description = "Utility used to store, backup, and transport files"
license = "GPL-3.0-or-later"
upstream = "https://www.gnu.org/software/tar/"

[dependencies]
runtime = ["glibc", "acl"]
build = ["make", "gcc"]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/tar/tar-1.35.tar.xz"
]
sha256 = ["4d62ff37342ec7aed748535323930c7cf94acf71c3591882b26a7ea50f3edc16"]

[build]
type = "autotools"
script = """
cd "${srcdir}/tar-${pkgver}"
sed -i -e 's/acl_get_file_at/tar_acl_get_file_at/g' \
       -e 's/acl_set_file_at/tar_acl_set_file_at/g' \
       -e 's/acl_delete_def_file_at/tar_acl_delete_def_file_at/g' src/xattrs.c
./configure --prefix=/usr
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""

