[package]
name = "qt6-wayland"
version = "6.8.2"
release = 1
description = "Provides APIs for Wayland client and compositor support in Qt6"
license = "LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only"
upstream = "https://www.qt.io/"
slot = "6"

[dependencies]
runtime = ["qt6-base", "qt6-declarative", "libxkbcommon", "libdrm", "wayland"]
build = ["cmake", "ninja", "pkgconf", "wayland-protocols", "vulkan-headers"]

[sources]
urls = ["https://download.qt.io/official_releases/qt/6.8/6.8.2/submodules/qtwayland-everywhere-src-6.8.2.tar.xz"]
sha256 = ["5e46157908295f2bf924462d8c0855b0508ba338ced9e810891fefa295dc9647"]

[build]
configure = """
cmake -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DINSTALL_BINDIR=lib/qt6/bin \
    -DINSTALL_INCLUDEDIR=include/qt6 \
    -DINSTALL_LIBDIR=lib \
    -DINSTALL_ARCHDATADIR=lib/qt6 \
    -DINSTALL_PLUGINSDIR=lib/qt6/plugins \
    -DINSTALL_QMLDIR=lib/qt6/qml \
    -DFEATURE_wayland_client=ON \
    -DFEATURE_wayland_server=ON \
    -DBUILD_TESTING=OFF
"""
compile = """
cmake --build build -j$(nproc)
"""
install = """
DESTDIR="${DESTDIR}" cmake --install build
"""
