[package]
name = "shadow"
version = "4.20.2"
release = 1
slot = "0"
description = "Password and account management utilities"
license = "BSD-3-Clause"
upstream = "https://github.com/shadow-maint/shadow"

[dependencies]
runtime = ["glibc", "acl", "libcap", "libseccomp"]
build = ["make", "gcc", "pkgconf"]

[sources]
urls = [
    "https://github.com/shadow-maint/shadow/releases/download/4.20.2/shadow-4.20.2.tar.xz"
]
sha256 = [
    "b89f432b75ae55a2d852b446d0365484795fdf533ab97d550e325fa15594a224"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/shadow-${pkgver}"
./configure --prefix=/usr --sysconfdir=/etc --without-libpam --disable-logind --with-acl --without-selinux --without-audit
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
