[package]
name = "m4"
version = "1.4.21"
release = 1
slot = "0"
description = "GNU Macro Processor"
license = "GPL-3.0-or-later"
upstream = "https://www.gnu.org/software/m4/"

[dependencies]
runtime = [
    "glibc",
]
build = [
    "make",
    "gcc",
]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/m4/m4-1.4.21.tar.xz",
]
sha256 = ["f25c6ab51548a73a75558742fb031e0625d6485fe5f9155949d6486a2408ab66"]

[build]
type = "autotools"
script = """
cd "${srcdir}/m4-${pkgver}"
./configure --prefix=/usr
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
