[package]
name = "gperf"
version = "3.3"
release = 1
slot = "0"
description = "Perfect hash function generator"
license = "GPL-3.0-or-later"
upstream = "https://www.gnu.org/software/gperf/"

[dependencies]
runtime = ["glibc"]
build = ["make", "gcc"]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/gperf/gperf-3.3.tar.gz"
]
sha256 = [
    "fd87e0aba7e43ae054837afd6cd4db03a3f2693deb3619085e6ed9d8d9604ad8"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/gperf-${pkgver}"
./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.1
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
