[package]
name = "dbus"
version = "1.16.2"
release = 1
slot = "0"
description = "Freedesktop.org message bus system"
license = "GPL-2.0-or-later"
upstream = "https://www.freedesktop.org/wiki/Software/dbus/"

[dependencies]
runtime = ["glibc", "expat", "libcap-ng", "eudev"]
build = ["gcc", "meson", "ninja", "pkgconf", "glib2", "python"]

[sources]
urls = [
    "https://dbus.freedesktop.org/releases/dbus/dbus-1.16.2.tar.xz"
]
sha256 = ["0ba2a1a4b16afe7bceb2c07e9ce99a8c2c3508e5dec290dbb643384bd6beb7e2"]

[build]
type = "meson"
script = """
cd "${srcdir}/dbus-${pkgver}"
meson setup build --prefix=/usr --buildtype=release
ninja -C build ${MAKEFLAGS}
DESTDIR="${DESTDIR}" ninja -C build install
"""
