[package]
name = "libcap"
version = "2.78"
release = 1
slot = "0"
description = "POSIX 1003.1e capabilities library and tools (setcap, getcap)"
license = "BSD-3-Clause OR GPL-2.0-only"
upstream = "https://sites.google.com/site/fullycapable/"

[dependencies]
runtime = ["glibc"]
build = []

[sources]
urls = [
    "https://kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.78.tar.xz"
]
sha256 = ["0d621e562fd932ccf67b9660fb018e468a683d7b827541df27813228c996bb11"]

[build]
type = "make"
script = """
cd "${srcdir}/libcap-${pkgver}"
make prefix=/usr lib=lib CC="${CC:-clang}" ${MAKEFLAGS}
make prefix=/usr lib=lib DESTDIR="${DESTDIR}" install
"""
