[package]
name = "parted"
version = "3.8"
release = 1
slot = "0"
description = "A program for creating, destroying, resizing, checking and copying partitions"
license = "GPL-2.0-or-later"
upstream = "https://www.gnu.org/software/parted/parted.html"

[dependencies]
runtime = ["glibc", "util-linux"]
build = ["make", "gcc", "pkgconf"]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/parted/parted-3.7.tar.xz"
]
sha256 = [
    "a2b7811f47b0ddb1f7b1d0aa456f7c1270da70708ce231c2fe054c7199eafa63"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/parted-${pkgver}"
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-static
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
