[package]
name = "iptables"
version = "1.8.13"
release = 1
slot = "0"
description = "Linux kernel packet filtering and NAT control utility"
license = "GPL-2.0-only"
upstream = "https://netfilter.org/projects/iptables/"

[dependencies]
runtime = ["glibc"]
build = ["make", "gcc", "pkgconf"]

[sources]
urls = [
    "https://netfilter.org/projects/iptables/files/iptables-1.8.11.tar.xz"
]
sha256 = [
    "1afcd33da9e8f913ace6a2126788162e207e26f5d5e29c6573c0e581ffc58b99"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/iptables-${pkgver}"
./configure --prefix=/usr --sbindir=/usr/bin --disable-nftables
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
