[package]
name = "alacritty"
version = "0.17.0"
release = 1
slot = "0"
description = "A cross-platform, GPU-accelerated terminal emulator"
license = "GPL-2.0-or-later"
upstream = "https://github.com/alacritty/alacritty"

[dependencies]
runtime = ["glibc", "freetype", "fontconfig", "libxi", "libxcursor", "libxkbcommon", "libxrandr", "libxcb"]
build = ["gcc", "rust", "mold", "clang", "llvm", "cmake", "ncurses", "pkgconf", "libxcb"]

[sources]
urls = [
    "https://github.com/alacritty/alacritty/archive/refs/tags/v0.17.0.tar.gz"
]
sha256 = ["fa03da86b110adcaaf9f476ee5de8ce1e59b913b2cf4e5d0374bf70af9c092c7"]

[build]
type = "cargo"
script = """
cd "${srcdir}/alacritty-${pkgver}"
cargo build --release --locked
install -Dm755 "target/release/alacritty" "${DESTDIR}/usr/bin/alacritty"
"""
