[package]
name = "pam"
version = "1.7.2"
release = 1
description = "Pluggable Authentication Modules for Linux"
license = "BSD-3-Clause OR GPL-2.0-or-later"
upstream = "https://github.com/linux-pam/linux-pam"
slot = "0"

[dependencies]
runtime = ["glibc"]
build = ["gcc", "make", "flex", "bison", "linux-headers", "pkgconf"]

[sources]
urls = ["https://github.com/linux-pam/linux-pam/releases/download/v1.7.2/Linux-PAM-1.7.2.tar.xz"]
sha256 = ["3d86b6383fb5fd9eb9578d2cd47d92801191f4bf3f9bc61419bfefc8aa1e531a"]

[build]
configure = """
./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --libdir=/usr/lib \
    --sbindir=/usr/bin \
    --disable-regenerate-docu \
    --disable-nis \
    --disable-nls
"""
compile = """
make -j$(nproc)
"""
install = """
make DESTDIR="${DESTDIR}" install
mkdir -p "${DESTDIR}/etc/pam.d"
cat << 'EOF' > "${DESTDIR}/etc/pam.d/other"
# Default fallback PAM configuration
auth        required    pam_deny.so
account     required    pam_deny.so
password    required    pam_deny.so
session     required    pam_deny.so
EOF
"""
