[package]
name = "lsof"
version = "4.99.7"
release = 1
slot = "0"
description = "Lists information about files opened by processes"
license = "custom"
upstream = "https://github.com/lsof-org/lsof"

[dependencies]
runtime = [
    "glibc",
]
build = [
    "make",
    "gcc",
]

[sources]
urls = [
    "https://github.com/lsof-org/lsof/archive/refs/tags/4.99.7.tar.gz",
]
sha256 = ["bac1b0acbc50aede42fc97dffaa0b0475e97973e36a6351de5f349c6155afc68"]

[build]
type = "autotools"
script = """
cd "${srcdir}/lsof-${pkgver}"
./Configure -n linux
make ${MAKEFLAGS}
install -Dm755 lsof "${DESTDIR}/usr/bin/lsof"
"""
