[package]
name = "libxrandr"
version = "1.5.5"
release = 1
slot = "0"
description = "X11 RandR extension library"
license = "MIT"
upstream = "https://xorg.freedesktop.org/"

[dependencies]
runtime = ["glibc", "libxcb"]
build = ["make", "gcc", "pkgconf"]

[sources]
urls = [
    "https://xorg.freedesktop.org/archive/individual/lib/libXrandr-1.5.5.tar.xz"
]
sha256 = [
    "72b922c2e765434e9e9f0960148070bd4504b288263e2868a4ccce1b7cf2767a"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/libXrandr-${pkgver}"
./configure --prefix=/usr --disable-static
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
