[package]
name = "procps-ng"
version = "4.0.7"
release = 1
slot = "0"
description = "Utilities for monitoring your system and its processes (ps, top, free)"
license = "GPL-2.0-or-later"
upstream = "https://gitlab.com/procps-ng/procps"

[dependencies]
runtime = ["glibc", "ncurses"]
build = ["make", "gcc", "pkgconf"]

[sources]
urls = [
    "https://gitlab.com/procps-ng/procps/-/archive/v4.0.7/procps-v4.0.7.tar.gz"
]
sha256 = ["468dfe0f29a77498286b459fcc33e24fcc2031c11a890244ba9cf1481a4f5df7"]

[build]
type = "autotools"
script = """
cd "${srcdir}/procps-v4.0.4"
./autogen.sh && ./configure --prefix=/usr --sysconfdir=/etc --without-systemd
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
