[package]
name = "make"
version = "4.4.1"
release = 1
slot = "0"
description = "GNU Make utility to maintain groups of programs"
license = "GPL-3.0-or-later"
upstream = "https://www.gnu.org/software/make/"

[dependencies]
runtime = ["glibc"]
build = []

[sources]
urls = [
    "https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz"
]
sha256 = ["dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3"]

[build]
type = "autotools"
script = """
cd "${srcdir}/make-${pkgver}"
./configure --prefix=/usr --without-guile
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
