[package]
name = "openrc"
version = "0.64.1"
release = 1
slot = "0"
description = "Service and init manager for Kura Linux"
license = "BSD-2-Clause"
upstream = "https://github.com/OpenRC/openrc"

[dependencies]
runtime = ["glibc", "ncurses"]
build = ["meson", "ninja", "pkgconf", "make"]

[sources]
urls = [
    "https://github.com/OpenRC/openrc/archive/refs/tags/0.64.tar.gz"
]
sha256 = [
    "56d6d24c7fd2ca15d1abd1fb82ce5430629a71acb2c3fa12760300243dbd0baa"
]

[build]
type = "meson"
script = """
cd "${srcdir}/openrc-${pkgver}"
meson setup build --prefix=/ --sysconfdir=/etc --libdir=/lib --sbindir=/sbin -Dpam=false -Dnewnet=true
ninja -C build ${MAKEFLAGS}
DESTDIR="${DESTDIR}" ninja -C build install
"""
