[package]
name = "gh"
version = "2.101.0"
release = 1
slot = "0"
description = "The GitHub CLI"
license = "MIT"
upstream = "https://github.com/cli/cli"

[dependencies]
runtime = ["glibc", "git"]
build = ["gcc", "make", "go"]

[sources]
urls = [
    "https://github.com/cli/cli/archive/refs/tags/v2.101.0.tar.gz"
]
sha256 = ["a266fe8575c0e061b987920c1831a15f71bf0036a8729a5ebb93c2fb0164899c"]

[build]
type = "custom"
script = """
cd "${srcdir}/gh-${pkgver}"
go build -o "gh" .
install -Dm755 "gh" "${DESTDIR}/usr/bin/gh"
"""
