[package]
name = "gh"
version = "2.102.0"
release = 1
slot = "0"
description = "The GitHub CLI"
license = "MIT"
upstream = "https://github.com/cli/cli"

[dependencies]
runtime = ["glibc", "git"]
build = ["gcc", "make", "go"]

[sources]
urls = [
    "https://github.com/cli/cli/archive/refs/tags/v2.101.0.tar.gz"
]
sha256 = [
    "08bf0ef8b4409893889175e0f5279d30d6edd96465816042c0d7c72eac598158"
]

[build]
type = "custom"
script = """
cd "${srcdir}/gh-${pkgver}"
go build -o "gh" .
install -Dm755 "gh" "${DESTDIR}/usr/bin/gh"
"""
