[package]
name = "extra-cmake-modules"
version = "6.30.0"
release = 1
description = "Extra modules and scripts for CMake used by KDE Frameworks"
license = "BSD-2-Clause"
upstream = "https://invent.kde.org/frameworks/extra-cmake-modules"
slot = "6"

[dependencies]
runtime = []
build = ["cmake"]

[sources]
urls = ["https://download.kde.org/stable/frameworks/6.30/extra-cmake-modules-6.30.0.tar.xz"]
sha256 = ["22c9f7ff930dae7329faebf2942d2424f4a298c43bb3f11e217be6b12f227f6e"]

[build]
configure = """
cmake -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_TESTING=OFF \
    -DBUILD_HTML_DOCS=OFF \
    -DBUILD_MAN_DOCS=OFF
"""
compile = """
cmake --build build -j$(nproc)
"""
install = """
DESTDIR="${DESTDIR}" cmake --install build
"""
