[package]
name = "libcap-ng"
version = "0.9.6"
release = 1
slot = "0"
description = "Alternate POSIX capabilities library"
license = "LGPL-2.1-or-later AND GPL-2.0-or-later"
upstream = "https://people.redhat.com/sgrubb/libcap-ng/"

[dependencies]
runtime = ["glibc"]
build = ["make", "gcc", "autoconf", "automake", "libtool"]

[sources]
urls = [
    "https://github.com/stevegrubb/libcap-ng/archive/refs/tags/v0.9.6.tar.gz"
]
sha256 = [
    "399040138e0ca62fa2bcabd63da9af4431a246ef7a654561a0ca3cb00010a539"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/libcap-ng-${pkgver}"
touch NEWS
autoreconf -fiv
./configure --prefix=/usr --sysconfdir=/etc --without-python --without-python3
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
