[package]
name = "openssh"
version = "10.5p1"
release = 1
slot = "0"
description = "Premier connectivity tool for remote login with the SSH protocol"
license = "BSD-2-Clause AND BSD-3-Clause AND MIT"
upstream = "https://www.openssh.com/"

[dependencies]
runtime = [
    "glibc",
    "openssl",
    "zlib",
    "libcap",
]
build = [
    "make",
    "gcc",
    "pkgconf",
]

[sources]
urls = [
    "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-10.5p1.tar.gz",
]
sha256 = ["d44d28a839ea9daf969cc69150fde59910b2b39361dad81a3bd6cbd19218db11"]

[build]
type = "autotools"
script = """
cd "${srcdir}/openssh-${pkgver}"
./configure --prefix=/usr --sysconfdir=/etc/ssh --with-ssl-dir=/usr --with-privsep-path=/var/empty --without-pam
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
