[package]
name = "lazygit"
version = "0.66.0"
release = 1
slot = "0"
description = "Simple terminal UI for git commands"
license = "GPL-2.0-or-later"
upstream = "https://github.com/jesseduffield/lazygit"

[dependencies]
runtime = ["glibc", "git"]
build = ["gcc", "go"]

[sources]
urls = [
    "https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.65.1.tar.gz"
]
sha256 = [
    "704b14509dae4c0212754d60d1c00181aea79c0734aafa2c83c89301dba1aefd"
]

[build]
type = "custom"
script = """
cd "${srcdir}/lazygit-${pkgver}"
go build -o "lazygit" .
install -Dm755 "lazygit" "${DESTDIR}/usr/bin/lazygit"
"""
