[package]
name = "fastfetch"
version = "2.68.1"
release = 1
slot = "0"
description = "Like neofetch, but much faster because written in C (Latest 2.38.0)"
license = "MIT"
upstream = "https://github.com/fastfetch-cli/fastfetch"

[dependencies]
runtime = ["glibc", "zlib"]
build = ["cmake", "ninja", "pkgconf", "gcc"]

[sources]
urls = [
    "https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.68.1.tar.gz"
]
sha256 = ["c268cfcd230cc7ed5447fb34ed21bf4977315c7104356a39388b6ba784ad11b0"]

[build]
type = "cmake"
script = """
cd "${srcdir}/fastfetch-${pkgver}"
cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
ninja -C build ${MAKEFLAGS}
DESTDIR="${DESTDIR}" ninja -C build install
"""
