[package]
name = "openssl"
version = "4.1.0-beta2"
release = 1
slot = "3"
description = "Robust, commercial-grade TLS/SSL cryptography toolkit"
license = "Apache-2.0"
upstream = "https://www.openssl.org/"

[dependencies]
runtime = ["glibc"]
build = ["make", "gcc", "perl"]

[sources]
urls = [
    "https://github.com/openssl/openssl/releases/download/openssl-4.1.0-alpha1/openssl-4.1.0-alpha1.tar.gz"
]
sha256 = [
    "457df0ec01a148954f843cb3589ff7465bdacc50250c7aba37e20f6c30c4e8b5"
]

[build]
type = "custom"
script = """
cd "${srcdir}/openssl-${pkgver}"
./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic enable-ec_nistp_64_gcc_128
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install_sw install_ssldirs
"""
