[package]
name = "jq"
version = "1.7.1"
release = 1
slot = "0"
description = "Command-line JSON processor"
license = "MIT"
upstream = "https://jqlang.github.io/jq/"

[dependencies]
runtime = [
    "glibc",
]
build = [
    "make",
    "gcc",
    "bison",
    "pkgconf",
]

[sources]
urls = [
    "https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-1.7.1.tar.gz",
]
sha256 = []

[build]
type = "autotools"
script = """
cd "${srcdir}/jq-${pkgver}"
./configure --prefix=/usr --disable-maintainer-mode
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
