[package]
name = "readline"
version = "8.3"
release = 1
slot = "0"
description = "GNU Readline command line editing library"
license = "GPL-3.0-or-later"
upstream = "https://tiswww.case.edu/php/chet/readline/rltop.html"

[dependencies]
runtime = ["glibc", "ncurses"]
build = ["make", "gcc"]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/readline/readline-8.3.tar.gz"
]
sha256 = [
    "fe5383204467828cd495ee8d1d3c037a7eba1389c22bc6a041f627976f9061cc"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/readline-${pkgver}"
./configure --prefix=/usr --with-curses --disable-static SHLIB_LIBS="-Wl,--no-as-needed -lncursesw"
make SHLIB_LIBS="-Wl,--no-as-needed -lncursesw" ${MAKEFLAGS}
make SHLIB_LIBS="-Wl,--no-as-needed -lncursesw" DESTDIR="${DESTDIR}" install
"""
