[package]
name = "libseccomp"
version = "2.6.1"
release = 1
slot = "0"
description = "Enhanced Seccomp library and kernel syscall filtering interface"
license = "LGPL-2.1-only"
upstream = "https://github.com/seccomp/libseccomp"

[dependencies]
runtime = ["glibc"]
build = ["make", "gcc"]

[sources]
urls = [
    "https://github.com/seccomp/libseccomp/releases/download/v2.6.1/libseccomp-2.6.1.tar.gz"
]
sha256 = ["501f66c667225d53791b97e1d7cf85ab764c297d04881f60f38f451c4b0ee1be"]

[build]
type = "autotools"
script = """
cd "${srcdir}/libseccomp-${pkgver}"
./configure --prefix=/usr --disable-static
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
