[package]
name = "diffutils"
version = "3.12"
release = 1
slot = "0"
description = "GNU diff, cmp, diff3 and sdiff programs"
license = "GPL-3.0-or-later"
upstream = "https://www.gnu.org/software/diffutils/"

[dependencies]
runtime = ["glibc"]
build = ["make", "gcc"]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/diffutils/diffutils-3.12.tar.xz"
]
sha256 = ["7c8b7f9fc8609141fdea9cece85249d308624391ff61dedaf528fcb337727dfd"]

[build]
type = "autotools"
script = """
cd "${srcdir}/diffutils-${pkgver}"
./configure --prefix=/usr
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
