[package]
name = "libtool"
version = "2.6.2"
release = 1
slot = "0"
description = "Generic library support script"
license = "GPL-2.0-or-later"
upstream = "https://www.gnu.org/software/libtool/"

[dependencies]
runtime = [
    "glibc",
    "m4",
]
build = [
    "make",
    "m4",
    "autoconf",
    "automake",
    "gcc",
]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/libtool/libtool-2.6.2.tar.xz",
]
sha256 = ["2ef1067c16c97db930fd740cc9bc3d3ba9a583804ae5ac42cc3e8719e49e191e"]

[build]
type = "autotools"
script = """
cd "${srcdir}/libtool-${pkgver}"
./configure --prefix=/usr
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
