[package]
name = "strace"
version = "7.2"
release = 1
slot = "0"
description = "Diagnostic, debugging and instructional userspace utility for Linux syscall tracing"
license = "LGPL-2.1-or-later"
upstream = "https://strace.io/"

[dependencies]
runtime = ["glibc"]
build = ["make", "gcc"]

[sources]
urls = [
    "https://github.com/strace/strace/releases/download/v7.2/strace-7.2.tar.xz"
]
sha256 = ["4bde6246926890dcee824f6e6ac42a06752f47d77e5097d86e3c0d6d4b709fe5"]

[build]
type = "autotools"
script = """
cd "${srcdir}/strace-${pkgver}"
./configure --prefix=/usr
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
