[package]
name = "glib2"
version = "2.82.5"
release = 1
slot = "0"
description = "Core low-level data structure and utility library from GNOME"
license = "LGPL-2.1-or-later"
upstream = "https://gitlab.gnome.org/GNOME/glib"

[dependencies]
runtime = ["glibc", "libffi", "pcre2", "zlib"]
build = ["meson", "ninja", "pkgconf", "gcc"]

[sources]
urls = [
    "https://download.gnome.org/sources/glib/2.82/glib-2.82.5.tar.xz"
]
sha256 = [
    "05c2031f9bdf6b5aba7a06ca84f0b4aced28b19bf1b50c6ab25cc675277cbc3f"
]

[build]
type = "meson"
script = """
cd "${srcdir}/glib-${pkgver}"
meson setup build --prefix=/usr -Dlibmount=disabled -Dman=false
ninja -C build ${MAKEFLAGS}
DESTDIR="${DESTDIR}" ninja -C build install
"""
