[package]
name = "dhcpcd"
version = "10.5.2"
release = 1
slot = "0"
description = "RFC2131 and RFC3315 compliant DHCP/DHCPv6 and IPv4LL dual-stack client"
license = "BSD-2-Clause"
upstream = "https://roy.marples.name/projects/dhcpcd"

[dependencies]
runtime = ["glibc", "openssl"]
build = ["make", "gcc", "pkgconf"]

[sources]
urls = [
    "https://github.com/NetworkConfiguration/dhcpcd/releases/download/v10.5.2/dhcpcd-10.5.2.tar.xz"
]
sha256 = ["3e476657fdb6eeb38b277da3a48d0ac0113ecce5858ebdcddff2b629faed52b4"]

[build]
type = "autotools"
script = """
cd "${srcdir}/dhcpcd-${pkgver}"
./configure --prefix=/usr --sysconfdir=/etc --rundir=/run
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
