[package]
name = "glibc"
version = "2.44"
release = 1
slot = "0"
description = "GNU C Library (Standard Core System C Library - Latest 2.44)"
license = "LGPL-2.1-or-later"
upstream = "https://www.gnu.org/software/libc/"

[dependencies]
runtime = ["linux-headers"]
build = ["gcc", "binutils", "make", "bison", "gawk", "sed"]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/glibc/glibc-2.44.tar.xz"
]
sha256 = ["37f600f2bef3c5e8300147059568b2a2e40a7ad6ccc65ce942556d49429cc667"]

[build]
type = "autotools"
script = """
mkdir -p build && cd build
../glibc-${pkgver}/configure --prefix=/usr --disable-profile --enable-kernel=6.6.0 --enable-stack-protector=strong --disable-werror libc_cv_slibdir=/usr/lib
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
