[package]
name = "groff"
version = "1.23.0"
release = 1
slot = "0"
description = "GNU troff text-formatting system"
license = "GPL-3.0-or-later"
upstream = "https://www.gnu.org/software/groff/"

[dependencies]
runtime = [
    "glibc",
]
build = [
    "make",
    "gcc",
    "bison",
    "pkgconf",
]

[sources]
urls = [
    "https://ftp.gnu.org/gnu/groff/groff-1.23.0.tar.gz",
]
sha256 = []

[build]
type = "autotools"
script = """
cd "${srcdir}/groff-${pkgver}"
./configure --prefix=/usr --without-x
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
