[package]
name = "sudo"
version = "1.9.16p2"
release = 1
slot = "0"
description = "Authority delegation tool allowing users to execute commands as root"
license = "ISC"
upstream = "https://www.sudo.ws/"

[dependencies]
runtime = [
    "glibc",
    "openssl",
    "zlib",
]
build = [
    "make",
    "gcc",
    "pkgconf",
]

[sources]
urls = [
    "https://www.sudo.ws/dist/sudo-1.9.16p2.tar.gz",
]
sha256 = []

[build]
type = "autotools"
script = """
cd "${srcdir}/sudo-${pkgver}"
./configure --prefix=/usr --sysconfdir=/etc --with-env-editor --without-pam
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
