[package]
name = "sudo"
version = "1.9.17p2"
release = 1
slot = "0"
description = "Authority delegation tool allowing users to execute commands as root"
license = "ISC"
upstream = "https://www.sudo.ws/"

[dependencies]
runtime = ["glibc", "openssl", "zlib"]
build = ["make", "gcc", "pkgconf"]

[sources]
urls = [
    "https://www.sudo.ws/dist/sudo-1.9.17p2.tar.gz"
]
sha256 = [
    "4a38a1ab3adb1199257edc2a7c4a2bd714665eb605b04368843b06dada2cfcfb"
]

[build]
type = "autotools"
script = """
cd "${srcdir}/sudo-${pkgver}"
./configure --prefix=/usr --sysconfdir=/etc --with-env-editor --without-pam
make ${MAKEFLAGS}
make DESTDIR="${DESTDIR}" install
"""
