[package]
name = "fish"
version = "4.9.3"
release = 1
slot = "0"
description = "Smart and user friendly shell intended mostly for interactive use"
license = "GPL-2.0-or-later"
upstream = "https://fishshell.com/"

[dependencies]
runtime = ["glibc", "gcc", "pcre2"]
build = ["gcc", "cmake", "git", "jq", "rust", "python-sphinx", "ninja"]

[sources]
urls = [
    "https://github.com/fish-shell/fish-shell/releases/download/4.9.3/fish-4.9.3.tar.xz"
]
sha256 = ["20998a25f73217ddcc19f499055fd587e9912d1ad6e7109120fbcf2871f0b98c"]

[build]
type = "cmake"
script = """
cd "${srcdir}/fish-${pkgver}"
cmake -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr
ninja -C build ${MAKEFLAGS}
DESTDIR="${DESTDIR}" ninja -C build install
"""
